title: Blog Bibliotheks- und Archivinformatik
author: Giulia D'Amico
email: giulia.damico@stud.fhgr.ch
description: > # this means to ignore newlines until "baseurl:"
  Lerntagebuch im Kurs Bibliotheks- und Archivinformatik HS2020


show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
